### ISSUE TITLE
modify bash submit script to accept queue argument

### ISSUE THREAD

**Issue by cjayb** [meeg-cfin/configurations#7]
Currently only `submit_to_isis` exists. Modify code to also allow specification of grid engine queue name ('short', 'long', 'isis', etc.). Refactor to take flag-based arguments, like so

```
submit_to_cluster --queue --n_threads=4 --some_other_option command_to_submit
```

_ALTERNATIVELY_: Re-write as a python script? Easier and more portable argument and error handling, but must be careful to keep python 2 so no troubles running on server machines' system python.

**Comment by MadsJensen** [comment]
+1 for python re-write. There is a MATLAB function for submitting to queues. And I do not think there is a need for a BASH wrapper.

**Comment by cjayb** [comment]
Deprecated, closing
